# conf/config.yaml
defaults:
  - env: level2        
  - uav: embedded      
  - reward: balanced   
  - _self_             

# 1. 算法选择 (关键点)
algo_name: "SAC"  # 之后你可以通过命令行改为 "SAC", "MASKABLE_PPO" 等

# 2. 训练全局参数
total_timesteps: 500000
seed: 42
exp_name: "DIFF_level2"  # 实验名称，用于区分不同实验的结果文件夹
# 启发式相关参数
run_heuristic_baseline: True  # 每次跑 RL 前是否自动跑一轮启发式对比
heuristic_timesteps: 20000    # 启发式跑多少步 (无需训练，2万步取均值足够了)
run_heuristic_reuse: False 
heuristic_reuse_input: DIFFUSION 
warmup_steps:20000 # 预热阶段的步数，期间完全使用启发式策略来填充经验回放缓冲区

# 3. 算法特定参数 (分类存放)
# 这样在 main.py 里可以直接拿 cfg.ppo 或 cfg.sac
ppo:
  learning_rate: 0.0003
  n_steps: 2048
  batch_size: 64
  gamma: 0.99

sac:
  learning_rate: 0.0003
  buffer_size: 100000
  tau: 0.005

diffusion:
  learning_rate: 0.0001   # <--- 学习率降低到 1e-4，防止扩散模型崩盘
  buffer_size: 200000      
  batch_size: 256         # <--- 扩散模型喜欢大 Batch Size，显存够就上 256
  tau: 0.005
  qne_temperature: 0.5  # <--- QNE 的温度参数，控制探索程度，默认 1.0 可以先试试

# Hydra 运行配置

hydra:
  run:
    dir: ./experiments/${algo_name}/${exp_name}_${now:%m%d_%H%M}
    # 禁用cwd切换，核心配置

  sweep:
    # 这是运行 python main.py -m 时生成的总目录
    dir: ./experiments/multirun/${now:%m%d_%H%M%S}
    # 这是每个子实验的文件夹名，根据参数动态生成
    subdir: crash${reward.CRASH}_succ${reward.SUCCESS}
  job:
    chdir: False